// AST for Lua
var LuaKeywords = {
    'and': true,
    'break': true,
    'do': true,
    'else': true,
    'elseif': true,
    'end': true,
    'false': true,
    'for': true,
    'function': true,
    'goto': true,
    'if': true,
    'in': true,
    'local': true,
    'nil': true,
    'not': true,
    'or': true,
    'repeat': true,
    'return': true,
    'then': true,
    'true': true,
    'until': true,
    'while': true
};
var LuaOtherTokens = {
    '+': true,
    '-': true,
    '*': true,
    '/': true,
    '%': true,
    '^': true,
    '#': true,
    '==': true,
    '~=': true,
    '<=': true,
    '>=': true,
    '<': true,
    '>': true,
    '=': true,
    '(': true,
    ')': true,
    '{': true,
    '}': true,
    '[': true,
    ']': true,
    '::': true,
    ';': true,
    ':': true,
    ',': true,
    '.': true,
    '..': true,
    '...': true,
    '[[': true,
    ']]': true
};
var LuaEscapes = "abfnrtv\\\"'z";
//# sourceMappingURL=lua-ast.js.map